### ISSUE TITLE
Library not loaded: @rpath/libXCGrapherPluginSupport.dylib 

### ISSUE THREAD

**Issue by Ewg777** [maxchuquimia/xcgrapher#13]
Setup: MacOS 11.6, M1 
Steps to reproduce:
```
brew tap maxchuquimia/scripts
brew install xcgrapher
gem install xcodeproj 
xcgrapher

```

Output 
```

dyld: Library not loaded: @rpath/libXCGrapherPluginSupport.dylib
  Referenced from: /opt/homebrew/bin/xcgrapher
  Reason: image not found
[1]    4170 abort      xcgrapher
```

**Comment by paxos** [comment]
I got it to work by cloning and by following the instructions in the readme (running `make`). Seems only to affect the `brew` version.

**Comment by omarzl** [comment]
This happens because in Apple Silicon computers the Homebrew installation directory changed.
You can sort this issue by setting manually the DYLD_LIBRARY_PATH before running xcgrapher:
```
export DYLD_LIBRARY_PATH="$(brew list xcgrapher | grep 'bin/xcgrapher' | sed 's#/bin/xcgrapher##')/lib"
xcgrapher --project Example.xcodeproj --target Example --pods
```

**Comment by maxchuquimia** [comment]
I finally got an M1 two days ago so I can test and resolve this soon, sorry for the delay everyone :)

**Comment by maxchuquimia** [comment]
Have forced the mapping of `@rpath` in the makefile (for now...?) and updated the brew formula.
It seems to work on both M1s and older machines now 🎉

**Comment by paxos** [comment]
Thank you!
