### ISSUE TITLE
Undefined method `real_path` when installed from homebrew

### ISSUE THREAD

**Issue by mpdifran** [maxchuquimia/xcgrapher#2]
I've installed the app via homebrew as outlined in the README. When I try and run it for my project, I get the following error:

```
$ xcgrapher --project Retailer.xcodeproj --target Retailer --apple

[XCGrapher] Loading plugin /usr/local/Cellar/xcgrapher/0.0.9/lib/libXCGrapherModuleImportPlugin.dylib
[XCGrapher] Generating list of source files in Retailer
[ShellTask] ruby -r xcodeproj -e 'Xcodeproj::Project.open("Retailer.xcodeproj").targets.filter do |t| t.name == "Retailer" end.first.source_build_phase.files.to_a.each do |f| puts f.file_ref.real_path.to_s end'
[main] -e:1:in `block in <main>': undefined method `real_path' for nil:NilClass (NoMethodError)
	from -e:1:in `each'
	from -e:1:in `<main>'
```

Is there something wrong with the command I ran, or is this a bug?

**Comment by maxchuquimia** [comment]
Hi! Thanks for finding this issue - I am unable to reproduce it however it appears to be an issue with how the `xcodeproj` gem lists compile sources.

The solution will likely be safely unwrapping `f.file_ref` before calling `real_path` on it - I should have time later today to look into it more.

Is there anything strange about the "Retailer" target that may be causing `xcodeproj` to have trouble reading it's compile sources?

**Comment by mpdifran** [comment]
Not that I know of, should be a pretty straightforward project. I can try testing on a brand new project as well.

**Comment by maxchuquimia** [comment]
Okay I _think_ I have a solution -- if you have time at some point are you able to run the following command and let me know if the output lists the files in your target?

```bash
ruby -r xcodeproj -e 'Xcodeproj::Project.open("Retailer.xcodeproj").targets.filter do |t| t.name == "Retailer" end.first.source_build_phase.files.to_a.reject do |f| f.file_ref.nil? end.each do |f| puts f.file_ref.real_path.to_s end'
```

Also I'd be curious to find out about the output on your machine of these two as well:

```bash
ruby -r xcodeproj -e 'Xcodeproj::Project.open("Retailer.xcodeproj").targets.filter do |t| t.name == "Retailer" end.first.source_build_phase.files.to_a.each do |f| puts f end'
ruby -r xcodeproj -e 'Xcodeproj::Project.open("Retailer.xcodeproj").targets.filter do |t| t.name == "Retailer" end.first.source_build_phase.files.to_a.each do |f| puts f.file_ref end'
```

I spent time time looking into XcodeProj's source but couldn't see any reason `file_ref` ends up nil..  Anyway, if the first snippet above lists files then I'll make a new version with it included. Thanks!

**Comment by mpdifran** [comment]
First command outputs a list of files, second command outputs `BuildFile` for every line, and last one outputs mostly `FileReference`, but there's a handful of file names, and like one or two blank lines.

**Comment by maxchuquimia** [comment]
Thanks! Definitely sounds like something weird in `xcodeproj`... anyway, I've published an update: please `brew update`  then `brew reinstall xcgrapher` and see if it works for your project now!

**Comment by mpdifran** [comment]
It worked! Thanks for looking into this, I'll close this issue now.
