### ISSUE TITLE
Support Private Remote Swift Packages

### ISSUE THREAD

**Issue by rogerluan** [maxchuquimia/xcgrapher#9]
I'd like to use this project to plot dependency graphs for private remote dependencies as well. This is tricky because it will need some sort of authentication.

Might relate to #8

**Comment by maxchuquimia** [comment]
Strange that it doesn't work for you.. I use XCGrapher at work and about half of our packages exist as private remotes - are you using ssh? It should just use your ssh key as any clone would...

**Comment by rogerluan** [comment]
Ah, fair enough. I didn't test this myself, actually, I just assumed it wouldn't work, because it doesn't work with local packages - but it actually makes sense now that you mentioned it. If this works for you, everything must be in place 💪 

Thanks for clarifying!
